- name: Download Trivy install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh
    dest: /tmp/trivy-install.sh
    mode: '0755'
  tags:
    - install
    - trivy

- name: Install Trivy
  become: true
  ansible.builtin.command:
    cmd: sh /tmp/trivy-install.sh -b /usr/local/bin v0.18.3
  args:
    creates: /usr/local/bin/trivy
  tags:
    - install
    - trivy

- name: Download ArgoCD CLI
  ansible.builtin.get_url:
    url: https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    dest: /usr/local/bin/argocd
    mode: '0755'
  become: true
  tags:
    - install
    - argocd

- name: Ensure Node.js and npm are installed
  become: true
  apt:
    name:
      - nodejs
      - npm
    state: present
    update_cache: yes
  tags:
    - install
    - ncc

- name: Install ncc globally with npm
  become: true
  community.general.npm:
    name: '@vercel/ncc'
    global: true
  tags:
    - install
    - ncc