- name: Set cli
  command: sudo apt install --yes {{ item }}
  with_items:
    - zsh
  tags:
    - install
    - cli-apps

- name: Install laptop configuration tools
  command: sudo apt install --yes {{ item }}
  with_items:
    - fzf
    - zoxide
  tags:
    - install
    - cli-apps

- name: Download autoenv install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hyperupcall/autoenv/main/scripts/install.sh
    dest: /tmp/autoenv-install.sh
    mode: '0755'
  tags:
    - install
    - cli-apps

- name: Check if autoenv is already installed
  become: true
  stat:
    path: /root/.autoenv
  register: autoenv_dir
  tags:
    - install
    - cli-apps

- name: Install autoenv from script
  become: true
  ansible.builtin.command:
    cmd: sh /tmp/autoenv-install.sh
  args:
    creates: /usr/local/bin/autoenv
  when: not autoenv_dir.stat.exists
  tags:
    - install
    - cli-apps

- name: Install text interaction tools
  command: sudo apt install --yes {{ item }}
  with_items:
    - bat
    - jq
    - yq
    - ripgrep
    - yamllint
  tags:
    - install
    - cli-apps

- name: Monitoring tools
  command: sudo apt install --yes {{ item }}
  with_items:
    - htop
    - btop
  tags:
    - install
    - cli-apps

- name: Install helper tools
  command: sudo apt install --yes {{ item }}
  with_items:
    - tree
    - watch
    - asciinema
  tags:
    - install
    - cli-apps

- name: Install TaskFile
  become: true
  snap:
    name: task
    state: present
    classic: true
  tags:
    - install
    - cli-apps
