- name: Download DevToys Linux .deb
  ansible.builtin.get_url:
    url: "https://github.com/DevToys-app/DevToys/releases/download/v2.0.8.0/devtoys_linux_x64.deb"
    dest: /tmp/devtoys-linux.deb
    mode: '0644'
  become: true
  tags:
    - install
    - ui-apps

- name: Install DevToys Linux .deb
  ansible.builtin.apt:
    deb: /tmp/devtoys-linux.deb
  become: true
  tags:
    - install
    - ui-apps

- name: Fix missing dependencies after DevToys install
  ansible.builtin.apt:
    update_cache: yes
    upgrade: no
    state: present
    force_apt_get: yes
  become: true
  tags:
    - install
    - ui-apps

- name: Install Spotify
  become: true
  snap:
    name: spotify
    state: present
  tags:
    - install
    - ui-apps

- name: Install Obsidian
  become: true
  snap:
    name: obsidian
    state: present
    classic: true
  tags:
    - install
    - ui-apps
