---
- name: Install MacOS Applications for Daily Driver Use
  hosts: localhost
  vars_files:
    - vars/main.yml

  handlers:
    - import_tasks: handlers/main.yml

  tasks:
  - include_tasks: tasks/preflight.yml
    tags: always, preflight
  - include_tasks: tasks/directories.yml
    tags: directories, install
  - include_tasks: tasks/ui-apps.yml
    tags: ui-apps, install
  - include_tasks: tasks/cli-apps.yml
    tags: cli-apps, install
  - include_tasks: tasks/cicd.yml
    tags: cicd, install
  - include_tasks: tasks/networking.yml
    tags: networking, install
  - include_tasks: tasks/git.yml
    tags: git-tools, gh-cli, install
  - include_tasks: tasks/kubernetes.yml
    tags: kubernetes, cluster-visualization, kubernetes-cli-tools, install
  - include_tasks: tasks/virtualization.yml
    tags: virtualization, install
  - include_tasks: tasks/docs.yml
    tags: documentation-tools, install
  - include_tasks: tasks/editors.yml
    tags: editors, install
  - include_tasks: tasks/aws.yml
    tags: aws, install
  - include_tasks: tasks/golang.yml
    tags: golang, golang-tools, install
  - include_tasks: tasks/iac.yml
    tags: iac, install
  - include_tasks: tasks/terminal.yml
    tags: terminal, install
  - include_tasks: tasks/custom-tools.yml
    tags: custom-tools, demo, install
  - include_tasks: tasks/nvim.yml
    tags: nvim, install
  - include_tasks: tasks/fonts.yml
    tags: fonts, install
  - include_tasks: tasks/dotfiles.yml
    tags: dotfiles, install
  - include_tasks: tasks/ghostty.yml
    tags: terminal, ghostty, install
  - include_tasks: tasks/zsh.yml
    tags: zsh, install
  - include_tasks: tasks/services.yml
    tags: services, ui-apps, install
