- name: Install homebrew packages
  command: brew install --formula {{ item }}
  with_items:
    - koekeishiya/formulae/yabai
    - koekeishiya/formulae/skhd
    - bat
    - act
    - jq
    - k9s
    - htop
    - neovim
    - wget
    - trivy
    - packer
    - go
    - tree
    - watch 
    - tfenv
    - goreleaser
    - markdown-toc
    - helm
    - tmux
    - fzf
    - terminal-notifier
    - helm-docs
    - kubectx
    - lazygit
    - lazydocker
  tags: 
    - install
    - cli-apps
