- name: Install AWS Packages
  command: brew install --formula {{ item }}
  with_items:
  - awscli
  - aws-iam-authenticator
  - eksctl
  tags:
  - install
  - aws
  - cli-tools

- name: Session Manager Plugin
  command: brew install --cask {{ item }}
  with_items:
  - session-manager-plugin
  tags:
  - install
  - aws
  - cli-tools
