- name: Install laptop configuration tools
  community.general.homebrew:
    name:
      - koekeishiya/formulae/yabai
      - koekeishiya/formulae/skhd
      - fzf
      - zoxide
    state: present
  notify:
    - Start Yabai
    - Start skhd
  tags:
    - install
    - cli-apps

- name: Install text interaction tools
  community.general.homebrew:
    name:
      - bat
      - jq
      - yq
      - ripgrep
      - yamllint
    state: present
  tags:
    - install
    - cli-apps

- name: Monitoring tools
  community.general.homebrew:
    name:
      - htop
      - btop
    state: present
  tags:
    - install
    - cli-apps

- name: Install homebrew packages
  community.general.homebrew:
    name:
      - tree
      - watch
      - autoenv
      - go-task
      - asciinema
    state: present
  tags:
    - install
    - cli-apps