- name: Install custom golang tools
  command: go install {{ item }}
  with_items:
  - github.com/user-cube/kontext@latest
  - github.com/user-cube/gclone@latest
  - github.com/user-cube/aws-cli-manager/v2@latest
  - github.com/user-cube/auth-refresher@latest
  tags:
  - install
  - custom-tools

- name: Install tools for demo
  command: brew install {{ item }}
  with_items:
  - imagemagick
  - gifsicle
  tags:
  - demo
  - custom-tools
