- name: Install custom golang tools
  ansible.builtin.command: go install {{ item }}
  loop: "{{ custom_go_tools }}"
  tags:
    - install
    - custom-tools

- name: Install tools for demo
  community.general.homebrew:
    name:
      - imagemagick
      - gifsicle
    state: present
  tags:
    - demo
    - custom-tools
