- name: Install VSCode Based editors
  community.general.homebrew_cask:
    name:
      - visual-studio-code
      - cursor
    state: present
  tags:
    - install
    - editors

- name: Install JetBrains Based editors
  community.general.homebrew_cask:
    name: jetbrains-toolbox
    state: present
  tags:
    - install
    - editors

- name: Install Neovim
  community.general.homebrew:
    name: neovim
    state: present
  tags:
    - install
    - editors
