- name: Install git tools
  community.general.homebrew:
    name:
      - git
      - git-secrets
      - gitleaks
      - lazygit
      - pre-commit
    state: present
  tags:
    - install
    - git-tools

- name: Install GH CLI
  community.general.homebrew:
    name: gh
    state: present
  tags:
    - install
    - gh-cli
    - git-tools
