- name: Install golang
  community.general.homebrew:
    name: go
    state: present
  tags:
    - install
    - golang
    - go
    - programming-languages

- name: Install golang tools
  community.general.homebrew:
    name: goreleaser
    state: present
  tags:
    - install
    - golang-tools
