- name: Install homebrew cask
  community.general.homebrew_cask:
    name:
      - devtoys
      - caffeine
      - macs-fan-control
      - spotify
      - raycast
      - font-hack-nerd-font
      - obsidian
      - betterdisplay
    state: present
  tags:
    - install
    - ui-apps
