- name: Download powerlevel10k theme
  ansible.builtin.git:
    repo: "{{ zsh_theme_repo }}"
    dest: "{{ zsh_theme_dest }}"
    depth: 1
  tags:
    - install
    - zsh

- name: Setup zsh
  community.general.homebrew:
    name:
      - zsh-syntax-highlighting
      - zsh-autosuggestions
    state: present
  tags:
    - install
    - zsh
