- name: Download powerlevel10k theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/powerlevel10k
    depth: 1
  tags:
    - install
    - zsh

- name: Setup zsh
  community.general.homebrew:
    name:
      - zsh-syntax-highlighting
      - zsh-autosuggestions
    state: present
  tags:
    - install
    - zsh
